### ISSUE TITLE
Cannot resolve symbol qlua

### ISSUE THREAD

**Issue by zxzzxxzx** [Enfernuz/quik-lua-rpc-java-client#8]
Hello,

I am trying to launch an example of lua rpc java client in IntelliJ Idea and currently it is saying thatsymbol qlua cannot be resolved from file SetSelectedRowResultPbDeserializer.java. Am I missing something or maybe some packages should be installed in order to launch the code? Could you please provide a short guide on how to launch it?

Thank you

**Comment by Enfernuz** [comment]
Hello!
I hope you use Maven to build the artifact because the application needs Java wrapper classes for the .proto files that are used both on the Java-client and the RPC service on the QUIK side. There's a maven Protobuf plugin hook in pom.xml, and in order to run properly, it needs a protobuf compiler's binary (`protoc` or `protoc.exe`) installed on your system and available through PATH (an alternative would be to run Maven manually to compile the wrappers, using the maven goal: `mvn compile -DprotocExecutable="path/to/directory/with/protoc/binary"`, i.e. 'mvn compile -DprotocExecutable="D:\\tmp\\protoc-3.7.1-win64\\bin"). You can download the protobuf compiler from here, for example: https://github.com/protocolbuffers/protobuf/releases/tag/v3.7.1

**Comment by zxzzxxzx** [comment]
Hello, thank you for reply.
an alternative method to run Maven (and/or protoc) manually did not work, need all of them in the path. Moreover, in pom need to indicate that protobuf version which is actually used (protoc.exe, it was 3.4.0 but i used 3.7.1), in other case generates an error emptyLongList() not found or something like that (see here https://www.bountysource.com/issues/70823858-emptylonglist-missing-when-generating-repeated-primatives-in-proto3-java). 

Anyway it works now, thank you

**Comment by zxzzxxzx** [comment]
By the way, do you have any examples of usage of such functions which require @NotNull final SomeClass.Args args as an argument? For example function 
`public @NotNull String qlua_sendTransaction(@NotNull final SendTransaction.Args args) {
        return makeRPC(SendTransaction.class, args, SendTransaction.Result.class).getResult();
    }`
cannot be called this way:

`final String result = rpcClient.qlua_sendTransaction( transaction_map);`
or
`final String result = rpcClient.qlua_sendTransaction("some_params");`
etc.
Thank you

**Comment by zxzzxxzx** [comment]
Also trying to send a message to the server and keep receiving an error

lua-rpc/impl\protobuf_request_response_serde.lua:23: Для типа процедуры protobuf '0' не найдено соответствующей QLua-функции.

`final Integer result = rpcClient.qlua_message("Hello, world!", Message.IconType.WARNING);`

May be that happens due to weekend and no trades actually made

**Comment by Enfernuz** [comment]
> 
> 
> By the way, do you have any examples of usage of such functions which require @NotNull final SomeClass.Args args as an argument? For example function
> `public @NotNull String qlua_sendTransaction(@NotNull final SendTransaction.Args args) { return makeRPC(SendTransaction.class, args, SendTransaction.Result.class).getResult(); }`
> cannot be called this way:
> 
> `final String result = rpcClient.qlua_sendTransaction( transaction_map);`
> or
> `final String result = rpcClient.qlua_sendTransaction("some_params");`
> etc.
> Thank you

It is simple -- just look at the SendTransaction.Args class and see how to instantiate it.

```java
final String result = rpcClient.qlua_sendTransaction( new SendTransaction.Args(transaction_map) );
```

**Comment by Enfernuz** [comment]
> 
> 
> Also trying to send a message to the server and keep receiving an error
> 
> lua-rpc/impl\protobuf_request_response_serde.lua:23: Для типа процедуры protobuf '0' не найдено соответствующей QLua-функции.
> 
> `final Integer result = rpcClient.qlua_message("Hello, world!", Message.IconType.WARNING);`
> 
> May be that happens due to weekend and no trades actually made

The QLua 'message' function doesn't even require a connection to the server. Could you provide the full source code which you're trying to run?

**Comment by zxzzxxzx** [comment]
solved.

in lua config.json need to change protobuf to json, after that code works correctly

**Comment by Enfernuz** [comment]
Sorry for the lack of documentation though. I hope I'll find time to write it.

**Comment by zxzzxxzx** [comment]
One more issue found. WHen trying to getCandlesByIndex

` final GetCandlesByIndex.Result result = rpcClient.qlua_getCandlesByIndex(new GetCandlesByIndex.Args("MyPrice", 0, 2046, 2));`

lua sends the following error

Error in poller:start. Call stack:
stack traceback:
	C:\Open_Broker_QUIK\lua\quik-lua-rpc/service.lua:376: in function <C:\Open_Broker_QUIK\lua\quik-lua-rpc/service.lua:375>
	[C]: in function 'error'
	C:\Open_Broker_QUIK\lua\quik-lua-rpc/utils\json.lua:67: in function <C:\Open_Broker_QUIK\lua\quik-lua-rpc/utils\json.lua:44>
	(tail call): ?
	C:\Open_Broker_QUIK\lua\quik-lua-rpc/utils\json.lua:82: in function <C:\Open_Broker_QUIK\lua\quik-lua-rpc/utils\json.lua:44>
	(tail call): ?
	C:\Open_Broker_QUIK\lua\quik-lua-rpc/utils\json.lua:82: in function <C:\Open_Broker_QUIK\lua\quik-lua-rpc/utils\json.lua:44>
	(tail call): ?
	C:\Open_Broker_QUIK\lua\quik-lua-rpc/utils\json.lua:124: in function <C:\Open_Broker_QUIK\lua\quik-lua-rpc/utils\json.lua:123>
	(tail call): ?
	C:\Open_Broker_QUIK\lua\quik-lua-rpc/service.lua:142: in function <C:\Open_Broker_QUIK\lua\quik-lua-rpc/service.lua:98>
	(tail c

Any ideas what this may be?

**Comment by zxzzxxzx** [comment]
mainly the error looks like the following:

Missing required creator property 'mcs' 

so quik is not sending out mcs (microseconds) data field. Is it possible to turn it on/off or maybe it was turned off in later releases of quik or maybe I need to remove this field from json schemas of qlua structures?

**Comment by zxzzxxzx** [comment]
issue solved.
in file json.lua need to throw out this line:
 `error("invalid table: sparse array")` still dont know what to do with it

moreover in file procedure_wrappers.lua added 2 stubs for getCandelsByIndex wrapper:

`candle.datetime.mcs = tostring(assert(0, string.format("Inserting stub for mcs %d.", i)))
      candle.does_exist = tostring(assert(candle.doesExist, string.format("Inserting stub for does_exist %d.", i)))`

mcs is missing from the quik and does_exist looks like a misspelling

**Comment by Enfernuz** [comment]
You definitely don't need to modify `json.lua` -- it's a library and has nothing to do with the QLua business logic. As for the `mcs` and `doesExist` field in datetime -- I thought they were mandatory. Turns out they weren't, so I'll do the patch ASAP.
Also, `does_exist` is not a misspelling -- I just didn't feel right to use CamelCase for Lua variables :) Now I think different, but the decision has been already made.

**Comment by Enfernuz** [comment]
When fixing another bug in the RPC service, I removed the lines with the `mcs` and `does_exist` fields' assignment, so now the `doesExist` field is propagated as is and appears on the client side properly named.
